# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: a5c35f0
_src_path: https://github.com/vivienm/copier-rust
author_fullname: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_license: MIT
copyright_year: 2024
package_name: vault-token-helper
pages_enabled: false
project_description: A token helper for HashiCorp Vault.
project_name: Vault Token Helper
project_type: bin
repository_hosted: true
repository_name: vault-token-helper
repository_namespace: vivienm
repository_provider: github.com
repository_url: https://github.com/vivienm/vault-token-helper
rust_toolchain: stable
